///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Pokemon {
/*
{
  "name": "Bulbasaur",
  "id": "#001",
  "imageurl": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
  "xdescription": "Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger.",
  "ydescription": "Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger.",
  "height": "2' 04\"",
  "category": "Seed",
  "weight": "15.2 lbs",
  "typeofpokemon": [
    "Grass"
  ],
  "weaknesses": [
    "Fire"
  ],
  "evolutions": [
    "#001"
  ],
  "abilities": [
    "Overgrow"
  ],
  "hp": 20,
  "attack": 30,
  "defense": 20,
  "special_attack": 30,
  "special_defense": 30,
  "speed": 30,
  "total": 160,
  "male_percentage": "87.5%",
  "female_percentage": "12.5%",
  "genderless": 0,
  "cycles": "20 ",
  "egg_groups": "Grass, Monster ",
  "evolvedfrom": "",
  "reason": "",
  "base_exp": "64"
} 
*/

  String? name;
  String? id;
  String? imageurl;
  String? xdescription;
  String? ydescription;
  String? height;
  String? category;
  String? weight;
  List<String>? typeofpokemon;
  List<String>? weaknesses;
  List<String>? evolutions;
  List<String>? abilities;
  int? hp;
  int? attack;
  int? defense;
  int? specialAttack;
  int? specialDefense;
  int? speed;
  int? total;
  String? malePercentage;
  String? femalePercentage;
  int? genderless;
  String? cycles;
  String? eggGroups;
  String? evolvedfrom;
  String? reason;
  String? baseExp;

  Pokemon({
    this.name,
    this.id,
    this.imageurl,
    this.xdescription,
    this.ydescription,
    this.height,
    this.category,
    this.weight,
    this.typeofpokemon,
    this.weaknesses,
    this.evolutions,
    this.abilities,
    this.hp,
    this.attack,
    this.defense,
    this.specialAttack,
    this.specialDefense,
    this.speed,
    this.total,
    this.malePercentage,
    this.femalePercentage,
    this.genderless,
    this.cycles,
    this.eggGroups,
    this.evolvedfrom,
    this.reason,
    this.baseExp,
  });
  Pokemon.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    id = json['id']?.toString();
    imageurl = json['imageurl']?.toString();
    xdescription = json['xdescription']?.toString();
    ydescription = json['ydescription']?.toString();
    height = json['height']?.toString();
    category = json['category']?.toString();
    weight = json['weight']?.toString();
    if (json['typeofpokemon'] != null) {
      final v = json['typeofpokemon'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      typeofpokemon = arr0;
    }
    if (json['weaknesses'] != null) {
      final v = json['weaknesses'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      weaknesses = arr0;
    }
    if (json['evolutions'] != null) {
      final v = json['evolutions'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      evolutions = arr0;
    }
    if (json['abilities'] != null) {
      final v = json['abilities'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      abilities = arr0;
    }
    hp = json['hp']?.toInt();
    attack = json['attack']?.toInt();
    defense = json['defense']?.toInt();
    specialAttack = json['special_attack']?.toInt();
    specialDefense = json['special_defense']?.toInt();
    speed = json['speed']?.toInt();
    total = json['total']?.toInt();
    malePercentage = json['male_percentage']?.toString();
    femalePercentage = json['female_percentage']?.toString();
    genderless = json['genderless']?.toInt();
    cycles = json['cycles']?.toString();
    eggGroups = json['egg_groups']?.toString();
    evolvedfrom = json['evolvedfrom']?.toString();
    reason = json['reason']?.toString();
    baseExp = json['base_exp']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['id'] = id;
    data['imageurl'] = imageurl;
    data['xdescription'] = xdescription;
    data['ydescription'] = ydescription;
    data['height'] = height;
    data['category'] = category;
    data['weight'] = weight;
    if (typeofpokemon != null) {
      final v = typeofpokemon;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['typeofpokemon'] = arr0;
    }
    if (weaknesses != null) {
      final v = weaknesses;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['weaknesses'] = arr0;
    }
    if (evolutions != null) {
      final v = evolutions;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['evolutions'] = arr0;
    }
    if (abilities != null) {
      final v = abilities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['abilities'] = arr0;
    }
    data['hp'] = hp;
    data['attack'] = attack;
    data['defense'] = defense;
    data['special_attack'] = specialAttack;
    data['special_defense'] = specialDefense;
    data['speed'] = speed;
    data['total'] = total;
    data['male_percentage'] = malePercentage;
    data['female_percentage'] = femalePercentage;
    data['genderless'] = genderless;
    data['cycles'] = cycles;
    data['egg_groups'] = eggGroups;
    data['evolvedfrom'] = evolvedfrom;
    data['reason'] = reason;
    data['base_exp'] = baseExp;
    return data;
  }
}
